### ISSUE TITLE
coherence between mp4ra.org and here

### ISSUE THREAD

**Issue by mikedo** [mp4ra/mp4ra#12]
This spec is correct and was updated not terribly long ago:  http://mp4ra.org/specs.html#MLP
This spec is not correct (an old version): https://mp4ra.github.io/mp4ra/specs.html#MLP 
This can be updated of course in github, but it implies that the two databases are not in sync.

**Comment by dwsinger** [comment]
The update to GH took longer than we expected and was based on a snapshot. I fixed MLP in place, and I thought I had scanned the RA emails to make sure we caught all the changes after the snapshot. Apologies.
