### ISSUE TITLE
CMAF brands

### ISSUE THREAD

**Issue by mikedo** [mp4ra/mp4ra#13]
We should probably get started adding the CMAF brands. In addition to the ones in the published 23000-19, we have the amendments and 3rd party ones that will be starting to queue up with increasing probability of collision. Is it worth organizing them in a CMAF subsection under brands? A subsection for CMAF Supplemental Data? Or are they all just "brands"?

**Comment by dwsinger** [comment]
CMAF indeed should be scanned...

**Comment by cconcolato** [comment]
Closing as redundant with #19, handled by #24
