### ISSUE TITLE
specification linkage is using the specification field rather than the linkname field

### ISSUE THREAD

**Issue by mikedo** [mp4ra/mp4ra#5]
OK, but then what is the linkname field for?

**Comment by cconcolato** [comment]
As used here https://github.com/mp4ra/mp4ra/blob/gh-pages/helper.js#L85 : 
- `specification` is the content of the first column in the [specs.html](https://mp4ra.github.io/mp4ra/specs.html) page and the clickable text content that appears in the specification column of the other pages (e.g. in the [brands page](https://mp4ra.github.io/mp4ra/filetype.html)). It should be human-readable, can contain spaces.
- `linkname` is used as the HTML fragment identifier. It does not have to be human readable, should not contain spaces, etc. It is the value that should be used in the CSV other than specification.csv.

Is it clearer?

**Comment by mikedo** [comment]
Makes sense.  Thanks.  FYI, I used ec-3 as the model for the entries I drafted (I did not create ec-3 but I can fix that one too).

**Comment by dwsinger** [comment]
Looking at Philip's PR, I think one uses the 'specification' in other CSV files, not the 'linkname', no?

**Comment by dwsinger** [comment]
helper.js seems to be searching based on the specification field, indeed. linkname is only used to make the anchor and hence fragment identifiers.

**Comment by mikedo** [comment]
yes, that was my observation of practice in the CSVs.  hence filing this issue.  I assume I should restore all the ones I changed?

**Comment by cconcolato** [comment]
Sorry for the confusion. I did not look carefully enough. 
@dwsinger modified the README file. Is that OK? If so, can you please close this issue.

**Comment by mikedo** [comment]
Yes
