### ISSUE TITLE
documentation is needed even for those familiar with the mp4ra site

### ISSUE THREAD

**Issue by mikedo** [mp4ra/mp4ra#6]
Some suggestions for a README...

1. Note that everything is under "CSV".
2. Note that if there if a new reference spec is needed for a new entry, then add that first in "specifications.csv"
3. Make the CSV filenames match the website labels exactly.
4. Clarify the specification linkage field (see #5 )

**Comment by cconcolato** [comment]
Can you confirm that the README is good and close?

**Comment by mikedo** [comment]
Good.
